# Generated by Django 6.0 on 2025-12-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Ваше имя', max_length=50, verbose_name='Имя'),
        ),
    ]
