# Generated by Django 6.0 on 2026-01-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_role_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
