# Generated by Django 6.0 on 2026-01-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_homework', 'Может создавать домашку'), ('can_update_homework', 'Может редактировать домашку'), ('can_view_homework', 'Может просматривать домашку'), ('can_delete_homework', 'Может удалять домашку')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
